bison: Autospec creation for update from version 3.5.4 to version 3.6.1
Adrian Vogelsgesang (7):
      larlr1.cc: Reject unsupported values for parse.lac
      style: stylistic cleanups in the C skeletons
      typo: succesful -> successful
      skeletons: prefer b4_parse_error_{case,bmatch} over manual solution
      c++: add support for parse.error=detailed
      c++: add parser::context for syntax error handling
      c++: add support for parse.error=custom

Akim Demaille (396):
      yacc: restructure and fix yysyntax_error
      glr.c: clarify yyreportSyntaxError
      yacc.c: avoid negations
      yacc.c: no longer support YYERROR_VERBOSE
      glr.c: no longer support YYERROR_VERBOSE
      doc: YYERROR_VERBOSE is no longer supported
      gitignore: update
      package: bump copyrights to 2020
      yacc.c: simplify use of YYDPRINTF
      regen
      todo: update
      CI: check on PPC64le, ARM64 and s390x
      yacc.c: introduce yysymbol_name
      yacc.c: style: double-quote the argument of b4_percent_define_get
      yacc.c: comment changes
      style: avoid redundancy in the tests
      c++: display the stack in the same order as in C
      c++: report the stack at the same places as in C
      d, java: use traces more alike that of C
      tests: fix AT_BISON_OPTION_PUSHDEFS, AT_BISON_OPTION_POPDEFS pairs
      tests: make AT_PARSE_PARAMS usable at the end of arguments
      regen
      yacc.c: extract yyerror_message_arguments
      yacc.c: store token numbers, not token strings
      yacc.c: style: avoid macros
      yacc.c: add custom error message generation
      yacc.c: check custom error messages
      tests: compute verbose error messages from the custom ones
      yacc.c: isolate yyexpected_tokens
      yacc.c: let custom error messages see the location
      yacc.c: check custom error messages with parse-params
      tests: a clearer test for parse-params
      yacc.c: pass the parse-params to yyreport_syntax_error
      yacc.c: portability to G++ 4.8
      regen
      glr.c: move some functions after the definition of types
      c: use yysymbol_name in traces
      yacc.c: add support for parse.error detailed
      yacc.c: tests: check detailed error messages
      regen
      bison: use detailed error messages
      regen
      yacc.c: escape trigraphs in detailed parse.error
      tests: check that detailed error messages preserve UTF-8 characters
      parsers: support translatable token aliases
      regen
      tests: check token internationalization
      parsers: issue tname with i18n markup
      yacc.c: fixes
      diagnostics: handle -fno-caret in the called functions
      diagnostics: translate bison's own tokens
      regen
      diagnostics: report syntax errors in color
      regen
      diagnostics: modernize bison's syntax errors
      regen
      git: update ignores
      bison: pretend to 3.6 already
      todo: update
      style: formatting changes
      tests: check custom error messages and push parsers
      examples: clean up
      examples: more tests
      examples: add an example of a push parser
      examples: add a complete example with all the bells and whistles
      doc: update Doxygen template
      doc: don't pretend trigonometry is part of arithmetics
      examples: be more robust to spaces in paths
      doc: simplify uses of @ref
      yacc.c: fix misleading indentation
      glr.c: rename yyStateNum as yy_state_t
      glr.c: move code around
      glr.c: introduce yyexpected_tokens and yysyntax_error_arguments
      glr.c: add support for parse.error=detailed
      glr.c: add support for parse.error=custom
      doc: document new features of parse.error
      examples: bistromathic: fix location tracking
      skeletons: add support for %code epilogue
      tests: comment changes
      java: example: rely on autoboxing
      java: example: improve
      java: example: properly track the locations
      java: avoid trailing white spaces
      java: formatting changes
      java: add access to the number of errors
      java: use the same calc tests as the other skeletons
      traces: write the "Reading a token" alone on its line
      traces: show the stack after reading a token
      traces: don't print the stack before the gotos
      java: examples: split in two
      java: examples: prefer switch to chains of else-if
      java: examples: fix the tracking of locations
      java: style: prefer putting the square brackets on the type
      java: style: avoid useless initializers
      java: tests: prepare the replacement of calculator tests
      java: tests: check location tracking in the calculator
      java: tests: remove now redundant tests
      java: tests: check push parsers like the others
      java: tests: remove now redundant tests
      m4: fix b4_token_format
      java: add support for parse.error=detailed
      java: introduce yyexpectedTokens
      java: make the syntax error format string translatable
      java: let the Context give access to yyntokens
      java: add support for parse.error custom
      java: provide Context with a more OO interface
      doc: clearly state that %yacc only makes sense with yacc.c
      doc: formatting changes
      skeletons: decorelate %token-table from verbose error messages
      skeletons: avoid b4_error_verbose_if, which is confusing
      java: revert "style: avoid useless initializers"
      doc: work around problems with PDF generation
      doc: formatting changes
      doc: spell check
      parse.error: document and diagnose the incompatibility with %token-table
      build: prefer %D% and %C% to hard coded values
      gnulib: update
      regen
      build: pacify syntax-check
      java: don't expose the Context's members
      java: check that parse.error custom|detailed work with push parsers
      java: beware not to alias the locations of the various symbols
      tests: check calls to yyerror from the user actions
      c++: simplify
      examples: bistromathic: demonstrate named references
      java: provide a Context ctor
      doc: simplify uses of references
      regen
      doc: document token internationalization
      doc: simplify the cross references
      doc: update recommandation for libtextstyle
      todo: update
      examples: fix c/calc
      style: remove useless declarations
      style: avoid using 'this' as an identifier
      style: comment changes
      bench.pl: clean up the dust
      c++: minor fixes
      c++: don't copy the lookahead
      examples: lexcalc: demonstrate location tracking
      examples: bistromathic: strengthen tests
      examples: bistromathic: don't use Flex
      gnulib: use readline
      examples: use consistently the GFDL header for readmes
      examples: bistromathic: demonstrate the use of yyexpected_tokens
      m4: decommission function generating macro
      m4: decommission b4_function_declare
      m4: remove b4_function_define and b4_function_declare
      bistromathic: check completion
      bistromathic: don't require spaces after operators for completion
      bistromathic: properly compute the lcp, as expected by readline
      style: formatting changes
      yacc.c: push: initialize the pstate variables in pstate_new
      yacc.c: push: undefine the pstate macros for the epilogue
      yacc.c: yyerror_range does not need to be preserved accross calls
      yacc.c: simplify yyparse_context_t member names
      README: point to tests/bison, and document --trace
      examples: bistromathic: simplify
      yacc.c: yypstate_expected_tokens
      yacc.c: style: prefer switch to if
      regen
      bench: die clearly on incorrect --grammar arguments
      bench: simplify the calc grammar
      bench: better error messages on invalid input
      bench: calc: add support for google benchmark
      bench: create a README file with benches
      bench: use a C++-11 compiler
      bench: use the same prefix in both bench methods
      bench: add a "latest" symlink
      bench: calc: work on a string instead of a file
      bench: calc: no need for super long inputs
      doc: c++: promote api.token.raw
      style: reduce length of private constant
      yacc.c: use negative numbers for errors in auxiliary functions
      skeletons: fix incorrect type for translatable tokens
      examples: don't use yysyntax_error_arguments
      tests: yacc.c: avoid yysyntax_error_arguments
      bison: avoid using yysyntax_error_arguments
      lalr1.cc: avoid using yysyntax_error_arguments
      skeletons: make yysyntax_error_arguments a private detail
      java: make yysyntaxErrorArguments a private detail
      regen
      todo: update
      c: use YYNOMEM instead of -2
      regen
      java: move away from _ for internationalization
      tests: recheck: work properly when the test suite was interrupted
      style: comment changes about token numbers
      yacc.c: introduce an enum that defines the symbol's number
      regen
      yacc.c: use yysymbol_type_t instead of int for yytoken
      yacc.c: also define a symbol number for the empty token
      regen
      yacc.c: prefer YYSYMBOL_YYERROR to YYSYMBOL_error
      regen
      bistromathic: use symbol numbers instead of YYTRANSLATE
      yysymbol_type_t: always assign an enumerator
      regen
      yacc.c: revert to not using yysymbol_type_t in the yytranslate table
      regen
      yacc.c: fix more errors from make maintainer-check-g++
      regen
      glr.c: use yysymbol_type_t, YYSYMBOL_YYEOF etc.
      glr.c, yacc.c: propagate yysymbol_type_t
      regen
      glr.c: remove the yySymbol alias
      c++: also use symbol_type_type
      c++: replace symbol_number_type with symbol_type_type
      d: use the SymbolType enum for symbol kinds
      examples: java: use explicit token identifiers
      java: use SymbolType
      java: fixes in SymbolType
      readme: more about the coding style
      c: rename yyparse_context_t as yypcontext_t
      style: rename yysyntax_error_arguments as yy_syntax_error_arguments
      todo: update
      news: update the yyreport_syntax_error example
      maint: post-release administrivia
      doc: remove obsolete release instructions
      c, c++: rename yysymbol_type_t as yysymbol_kind_t
      d, java: rename SymbolType as SymbolKind
      m4: rename b4_symbol_sid as b4_symbol_kind
      m4: we don't need undef_token_number
      doc: refer to the token kind rather than the token type
      skeletons: use consistently "kind" instead of "type" in the code
      bison: use consistently "token kind", not "token type"
      regen
      c: make the generated YYSTYPE nicer to read
      c: make the token kind definition nicer to read
      c: make the symbol kind definition nicer to read
      java: style: fix coding style
      java: use getExpectedTokens, not yyexpectedTokens
      java: rename Lexer.yyreportSyntaxError as reportSyntaxError
      java: prefer null to YYSYMBOL_YYEMPTY
      java: document new features
      skeletons: beware not to use yyarg when it's null
      todo: update
      java: also emit documenting comments for symbol kinds
      skeletons: introduce api.symbol.prefix
      symbols: minor fixes
      d: improvements on symbol kinds
      c++: improvements on symbol kinds
      todo: update
      style: rename YYNOMEM as YYENOMEM
      c++: fix generated headers
      glr.cc: remove dead code
      tokens: style: minor fixes
      tokens: properly define the "error" token kind
      tokens: define the "$undefined" token kind
      tokens: properly define the YYEOF token kind
      c++: remove the yy prefix from some functions
      diagnostics: replace "user token number" by "token code"
      skeletons: use "end of file" instead of "$end"
      skeletons: make the eof token translatable if i18n is enabled
      skeletons: use "invalid token" instead of "$undefined"
      skeletons: clarify the tag of special tokens
      c: rename yyexpected_tokens as yypcontext_expected_tokens
      doc: document yypcontext_t, and api.symbol.prefix
      doc: promote yytoken_kind_t, not yytokentype
      doc: use "code", not "number", for token (and symbol) kinds
      c, c++: also define YYEMPTY in yytoken_kind_t
      regen
      d: put YYEMPTY in the TokenKind
      doc: promote YYEOF
      doc: c++: document parser::context
      style: java: get closer to the Java style
      doc: java: SymbolKind, etc.
      java: fix names
      java: promote YYEOF rather that Lexer.EOF
      doc: more about the coding style
      gnulib: update
      doc: spell check
      examples: bistro: don't be lazy with switch
      style: comments changes about error handling
      skeletons: use symbol(-2, kind)
      doc: updates for 3.6
      doc: token_kind_type in C++
      c++: give public access to the symbol kind
      examples: beware of readline on macOS
      version 3.5.90
      maint: post-release administrivia
      tests: beware of portability issues with wc
      news: fix typo
      tokens: clean up the translation of special symbols
      style: fix comments
      i18n: also look in src/parse-gram.c
      c, c++: provide a default definition for N_
      diagnostics: fix a typo
      regen
      todo: update for YYERRCODE
      examples: bistromathic: demonstrate internationalization
      examples: bistromathic: shorten token description
      style: minor fixes
      style: clarify #endif
      bench: minor improvements
      bench: store in benches/012 rather than in benches/12
      style: c: fix a few minor issues about indentation of cpp directives
      skeletons: make the warning about implementation details clearer
      style: fix a few remaining 'type' instead of 'kind'
      style: glr.c: fix indentation issue
      style: prefer b4_has_translations_if
      style: glr.c: clarify
      all: prefer YYERRCODE to YYERROR
      c++: fix a few style issues
      c++: always define symbol_name
      c++: make valid to print the empty symbol
      doc: hacking tricks
      examples: bistromathic: comment changes
      examples: bistromathic: when quitting, close the current line
      examples: bistromathic: demonstrate error recovery
      c: don't emit an error message when the scanner returns YYERRCODE
      all: don't emit an error message when the scanner returns YYERRCODE
      todo: update
      regen
      scanner: bad character literals are errors
      scanner: avoid spurious errors about empty character literals
      dogfooding: use YYERRCODE in our scanner
      error: rename the error token from YYERRCODE to YYerror
      java: clean up the definition of token kinds
      style: c++: s/type/kind/ where appropriate
      yacc.c: install backward compatibility for YYERRCODE
      tests: beware of portability of readline
      style: avoid gettextize warnings
      package: fix distcheck
      doc: document YYEOF, YYUNDEF and YYerror
      gnulib: update
      build: fix syntax-check issues
      version 3.5.91
      maint: post-release administrivia
      yacc.c: avoid the use of a temporary
      c++: use modern idioms to make classes non-copyable
      news: make it more consistent
      java: comment changes
      java: avoid useless work
      java: style: fix coding style of yyerror/reportSyntaxError
      java: add missing i18n requests
      doc: document the exit status
      style: more documentation about errs
      todo: more
      style: comment changes
      java: fix coding style
      doc: java supports push parsers since 3.0 (2013-07-25)
      yacc.c: improve formatting of the generated code
      c++: provide backward compatibility on by_type
      examples: beware of the portability of flex --header-file
      examples: beware of portability issues with readline
      examples: beware of intl portability issues
      tests: beware of mbswidth portability issues
      doc: clarify what a location is
      java: demonstrate push parsers
      gnulib: update
      news: update for 3.5.92
      version 3.5.92
      maint: post-release administrivia
      tests: beware of portability issues of sh
      bistromathic: beware of portability of readline
      flex: fix incorrect use of Automake conditional
      bistromathic: beware of portability issues with strndup
      c++: be compatible with the pre-3.6 way to get a symbol's kind
      build: fix warnings (shown on IRIX)
      examples: beware of portability issues with cmp
      bistromathic: beware of portability issues of readline on AIX
      tests: really skip tricky multichar test on Cygwin
      gnulib: update
      news: update for 3.5.93
      version 3.5.93
      maint: post-release administrivia
      tests: beware of portability issues with diff -u
      examples: beware of portability issues with sh's trap
      examples: beware of strnlen portability issues
      todo: update
      glr.c: beware of portability issues with PTRDIFF_MAX
      tests: beware of wchar_t portability issues on AIX
      doc: beware of timestamp issues on Haiku
      examples: fix handling of syntax errors
      all: fix the interface of yyexpected_tokens
      doc: restructure the push parser documentation
      doc: document yypstate_expected_tokens
      version 3.5.94
      maint: post-release administrivia
      doc: clarify the glossary item about kinds
      doc: complete the table of symbols
      news: prepare for 3.6
      doc: fix the generation of the man page
      regen
      examples: beware of portability issue on Windows
      version 3.6
      maint: post-release administrivia
      yacc.c: restore ansi-c compatibility
      style: minor fixes
      build: also provide lzip compressed tarballs
      examples: beware of ~/.inputrc
      c++: make parser::symbol_name public
      c++: provide yy::parser::symbol_type::name
      c++: style: reorder generated code
      version 3.6.1

Akimn Demaille (1):
      build: fix typo

Bruno Haible (1):
      package: fix a link error on IRIX

Victor Morales Cayuela (1):
      diagnostics: modernize the display of submessages

* Noteworthy changes in release 3.6.1 (2020-05-10) [stable]

** Bug fixes

  GNU readline portability issues.

  In C++, yy::parser::symbol_name is now a public member, as was intended.

** New features

  In C++, yy::parser::symbol_type now has a public name() member function.

* Noteworthy changes in release 3.6 (2020-05-08) [stable]

** Backward incompatible changes

(NEWS truncated at 15 lines)